name: Deploy Tenner og Trivsel

on:
  push:
    branches: [ main ]
  pull_request: # Gjør at Dependabot-PRs trigger build-sjekken
    branches: [ main ]
  repository_dispatch:
    types: [google_drive_update] # Sjekk at denne teksten er identisk med event_type i curl
  workflow_dispatch:

# Legg til dette for å fjerne sikkerhetsadvarselen
permissions:
  contents: read
  pages: write      # Legg til denne hvis du bruker GitHub Pages
  id-token: write   # Trengs ofte for sikker autentisering mot sky-tjenester

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          PUBLIC_GOOGLE_API_KEY: ${{ secrets.PUBLIC_GOOGLE_API_KEY }}

      - name: Build Astro site
        run: npm run build
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_DRIVE_TJENESTER_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_TJENESTER_FOLDER_ID }}
          GOOGLE_DRIVE_MELDINGER_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_MELDINGER_FOLDER_ID }}
          PUBLIC_GOOGLE_API_KEY: ${{ secrets.PUBLIC_GOOGLE_API_KEY }}


      # Vi lagrer "dist"-mappen midlertidig slik at deploy-jobben kan bruke den
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
  deploy:
    needs: build
    # Denne jobben kjører KUN på push til main, Google Drive-oppdatering eller manuelt
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 # Endre til din region (f.eks. eu-west-1)

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://test2.aarrestad.com --acl public-read --delete

#        - name: Invalidate CloudFront Cache
#          run: |
#            aws cloudfront create-invalidation \
#              --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
#              --paths "/*"